In [1]:
import numpy as np

In [145]:
def BackPropagation(cache):
    numNeurons = (2,6,2)
    b = [np.random.randint(1,3,(y, 1)) for y in numNeurons[1:]]

    w = [np.random.randint(1,3,(x,y)) for x,y in zip(numNeurons[:-1], numNeurons[1:])]
    [print("w[{}]({})".format(i,w[i].shape)) for i in range(len(w[0]))]
    
    
    y = ([0],[1])
    nablaB = [np.random.randint(1,3,(y, 1)) for y in numNeurons[1:]]
    nablaW = [np.random.randint(1,3,(x,y)) for x,y in zip(numNeurons[:-1], numNeurons[1:])]
    
    
    a = [np.random.randint(1,3,(y,1)) for y in numNeurons]
    
    
    delta = (a[-1] - np.array(y)) * a[-1]*(1 - a[-1])
    nablaB[-1] = delta
    nablaW[-1] = delta.dot(a[-2].T)
    
    print("\ndelta({}): \n{}".format(delta.shape,delta))
    print("nablaB2: \n{}".format(nablaB))
    print("nablaW2: \n{}".format(nablaW[-1]))
    
    
    for l in range (2, len(numNeurons)):
        print("w: ", w[-l+1].shape)
        delta = w[-l+1].dot(delta) * a[-l]*(1 - a[-l])
        nablaB[-l] = delta
        nablaW[-l] = delta.dot(a[-l-1].T)
    
    return nablaB, nablaW
    

In [146]:

BackPropagation()

w[0]((2, 6))
w[1]((6, 2))

delta((2, 1)): 
[[-4]
 [-2]]
nablaB2: 
[array([[1],
       [1],
       [2],
       [2],
       [1],
       [2]]), array([[-4],
       [-2]])]
nablaW2: 
[[-8 -4 -8 -8 -8 -4]
 [-4 -2 -4 -4 -4 -2]]
w:  (6, 2)


([array([[20],
         [ 0],
         [24],
         [20],
         [24],
         [ 0]]), array([[-4],
         [-2]])], [array([[20, 20],
         [ 0,  0],
         [24, 24],
         [20, 20],
         [24, 24],
         [ 0,  0]]), array([[-8, -4, -8, -8, -8, -4],
         [-4, -2, -4, -4, -4, -2]])])