In [1]:
import numpy as np
import matplotlib.pyplot as plt
from Pad import PadZero
from FC import forwardPass, backPropagation
from Conv import feedForwardConv, Empty

In [2]:
m = 1
nH = 4
nW = 4
nC = 1
sizeFilter = 3
stride = 1
pad = 1
#x = np.random.randint(0,16,(m,nH,nW,nC))
x = np.array([1,2,0,2,2,1,0,0,2,0,0,0,2,2,0,0]).reshape(m,nH,nW,nC)
print("x{}: \n{}".format(x.shape,x[0,:,:,0]))
w = np.ones((sizeFilter,sizeFilter,nC), dtype = np.int32)
b = 0
hyperparameters = {"stride": stride, "padding":pad}
print("w: \n", w[:,:,0])


x(1, 4, 4, 1): 
[[1 2 0 2]
 [2 1 0 0]
 [2 0 0 0]
 [2 2 0 0]]
w: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
a, cache = feedForwardConv(x,w,b,hyperparameters, Empty)

print("a{}: \n{}".format(a.shape, a[0,:,:,0]))


a(1, 4, 4, 1): 
[[6. 6. 5. 2.]
 [8. 8. 5. 2.]
 [9. 9. 3. 0.]
 [6. 6. 2. 0.]]


In [4]:
a = a.reshape(a[0,0,:,0].shape[0] * a[0,:,0,0].shape[0], 1)

In [5]:
print("a{}: \n{}".format(a.shape,a))
print("a.shape[0]: ", a.shape[0])

a(16, 1): 
[[6.]
 [6.]
 [5.]
 [2.]
 [8.]
 [8.]
 [5.]
 [2.]
 [9.]
 [9.]
 [3.]
 [0.]
 [6.]
 [6.]
 [2.]
 [0.]]
a.shape[0]:  16


In [6]:
size = [a.shape[0],3,2]
m = 1
y = np.array([1,0]).reshape(size[-1],m)
#x = np.array([[1,2,3,1],[3,2,1,1]]).reshape(size[0],m)
x = a
w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
print(w[1].shape)
learningRate = 1
caches2 = []
hyperparameters = {"learningRate":learningRate}

(2, 3)


In [7]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters)

print("yHat: \n",yHat)

yHat: 
 [[0.9999546 ]
 [0.99987661]]


In [8]:
caches2.append(cache)



In [11]:
biases, activations = backPropagation(caches2)
print(activations.shape)
[print(activ) for activ in activations]

(3, 16)
[0.23189053 0.23189053 0.19324211 0.07729684 0.30918737 0.30918737
 0.19324211 0.07729684 0.34783579 0.34783579 0.11594526 0.
 0.23189053 0.23189053 0.07729684 0.        ]
[0.46382318 0.46382318 0.38651931 0.15460773 0.6184309  0.6184309
 0.38651931 0.15460773 0.69573476 0.69573476 0.23191159 0.
 0.46382318 0.46382318 0.15460773 0.        ]
[0.69573476 0.69573476 0.57977897 0.23191159 0.92764635 0.92764635
 0.57977897 0.23191159 1.04360215 1.04360215 0.34786738 0.
 0.69573476 0.69573476 0.23191159 0.        ]


[None, None, None]

In [13]:
a = a.reshape(m,nH,nW,nC)
print("a{}: \n{}".format(a.shape, a[0,:,:,0]))

a(1, 4, 4, 1): 
[[6. 6. 5. 2.]
 [8. 8. 5. 2.]
 [9. 9. 3. 0.]
 [6. 6. 2. 0.]]
