In [103]:
import numpy as np
import matplotlib.pyplot as plt
from Pad import PadZero
from FC import forwardPass, backPropagation
from Conv import feedForwardConv, Empty

In [104]:
def CacheForConv(cache1,cache2):
    cache = [cache1[0][0].copy(),cache2[1].copy(),cache2[2],cache2[3].copy()]
    shape = cache2[0].shape
    cache[0] = cache[0].reshape(shape)
    return cache

In [105]:
def backPropagationConv(cache, delta, activationFunctionPrime = Empty):
    (a,w,b,hyperparameters) = cache
    (m,nH,nW,nC) = a.shape
    (f,f,nC) = w.shape
    stride = hyperparameters["stride"]
    pad = hyperparameters["padding"]
    nablaW = np.zeros(w.shape)
    print("a{}: \n{}".format(a.shape,a[0,:,:,0]))
    print("w{}: \n{}".format(w.shape,w[...,0]))
    for m1 in range(m):
        for i,h1 in enumerate(range(0,nH-f+1,stride)):
            for j,w1 in enumerate(range(0,nW-f+1,stride)):
                for c1 in range(nC):
                    
                    '''print("\n\nm1: {}\ni:{} h1:{}\nj:{} w1:{}\nc1:{}".format(m1,i,h1,j,w1,c1))
                    print("W1: \n",nablaW[:,:,c1])
                    print("a: \n", a[m1,h1:h1+f,w1:w1+f,c1])
                    print("delta: \n",delta[h1:h1+f,w1:w1+f])'''
                    
                    newW = a[m1,h1:h1+f,w1:w1+f,c1] * delta[h1:h1+f,w1:w1+f]
                    nablaW[:,:,c1] += newW
                    
                    '''print("W2: \n",newW)
                    print("W: \n",nablaW[:,:,c1])'''
                    
    return nablaW

In [106]:
m = 1
nH = 4
nW = 4
nC = 1

sizeFilter = 3
stride = 1
pad = 1

#x = np.random.randint(0,16,(m,nH,nW,nC))
x = np.array([1,2,0,2,2,1,0,0,2,0,0,0,2,2,0,0]).reshape(m,nH,nW,nC)
print("x{}: \n{}".format(x.shape,x[0,:,:,0]))

wConv = np.ones((sizeFilter,sizeFilter,nC), dtype = np.int32)
print("\nwConv{}: \n{}".format(wConv.shape, wConv[:,:,0]))

b = 0

hyperparameters = {"stride": stride, "padding":pad}
caches2 = []

x(1, 4, 4, 1): 
[[1 2 0 2]
 [2 1 0 0]
 [2 0 0 0]
 [2 2 0 0]]

wConv(3, 3, 1): 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [107]:
a1, cache = feedForwardConv(x,wConv,b,hyperparameters, Empty)

print("a1{}: \n{}".format(a1.shape, a1[0,:,:,0]))


a1(1, 4, 4, 1): 
[[6. 6. 5. 2.]
 [8. 8. 5. 2.]
 [9. 9. 3. 0.]
 [6. 6. 2. 0.]]


In [108]:
a2, cache = feedForwardConv(a1,wConv,b,hyperparameters, Empty)

print("a2{}: \n{}".format(a2.shape, a2[0,:,:,0]))

a2(1, 4, 4, 1): 
[[28. 38. 28. 14.]
 [46. 59. 40. 17.]
 [46. 56. 35. 12.]
 [30. 35. 20.  5.]]


In [109]:
caches2.append(cache)

In [110]:
a2 = a2.reshape(a1[0,0,:,0].shape[0] * a1[0,:,0,0].shape[0], 1)

In [111]:
print("a2{}: \n{}".format(a2.shape,a2))

a2(16, 1): 
[[28.]
 [38.]
 [28.]
 [14.]
 [46.]
 [59.]
 [40.]
 [17.]
 [46.]
 [56.]
 [35.]
 [12.]
 [30.]
 [35.]
 [20.]
 [ 5.]]


In [112]:
#a = np.array([6,6,5,2,8,8,5,2,9,9,3,0,6,6,2,0], dtype = np.float).reshape(16,1)
#a = np.array([28,38,28,14,46,59,40,17,46,56,35,12,30,35,20,5], dtype = np.float).reshape(16,1)

size = [a2.shape[0],3,2]

m = 1

y = np.array([1,0]).reshape(size[-1],m)
#x = np.array([[1,2,3,1],[3,2,1,1]]).reshape(size[0],m)
x = a2
print("x{}: \n{}".format(x.shape,x))

#w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
w1 = np.array([[1,3,2,3,1,2,2,2,2,2,3,1,2,2,1,1],[1,1,2,1,1,3,1,3,3,1,3,3,2,3,1,1],[1,3,2,3,1,3,1,2,3,1,3,1,3,3,3,2]])
w2 = np.array([[1,2,1],[1,1,2]])
w = [w1,w2]
print("w: \n",w)

#b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
b1 = np.array([[1,3,3]]).reshape(3,1)
b2 = np.array([[1,2]]).reshape(2,1)
b = [b1,b2]
print("b: \n",b)

learningRate = 1

hyperparameters = {"learningRate":learningRate}


x(16, 1): 
[[28.]
 [38.]
 [28.]
 [14.]
 [46.]
 [59.]
 [40.]
 [17.]
 [46.]
 [56.]
 [35.]
 [12.]
 [30.]
 [35.]
 [20.]
 [ 5.]]
w: 
 [array([[1, 3, 2, 3, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 1, 1],
       [1, 1, 2, 1, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 1],
       [1, 3, 2, 3, 1, 3, 1, 2, 3, 1, 3, 1, 3, 3, 3, 2]]), array([[1, 2, 1],
       [1, 1, 2]])]
b: 
 [array([[1],
       [3],
       [3]]), array([[1],
       [2]])]


In [113]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters,Empty)

print("yHat: \n",yHat)

yHat: 
 [[4068.]
 [4207.]]


In [114]:
caches2.append(cache)



In [115]:
nablaB, nablaW, delta = backPropagation(caches2[1], Empty)
print(nablaW.shape)
[print(newW) for newW in nablaW]

(3, 16)
[9.54021263e+11 1.29474314e+12 9.54021263e+11 4.77010632e+11
 1.56732065e+12 2.01025909e+12 1.36288752e+12 5.79227196e+11
 1.56732065e+12 1.90804253e+12 1.19252658e+12 4.08866256e+11
 1.02216564e+12 1.19252658e+12 6.81443760e+11 1.70360940e+11]
[1.39077752e+12 1.88748378e+12 1.39077752e+12 6.95388762e+11
 2.28484879e+12 2.93056693e+12 1.98682503e+12 8.44400640e+11
 2.28484879e+12 2.78155505e+12 1.73847191e+12 5.96047510e+11
 1.49011878e+12 1.73847191e+12 9.93412517e+11 2.48353129e+11]
[1.62309155e+12 2.20276711e+12 1.62309155e+12 8.11545776e+11
 2.66650755e+12 3.42008577e+12 2.31870222e+12 9.85448443e+11
 2.66650755e+12 3.24618311e+12 2.02886444e+12 6.95610666e+11
 1.73902666e+12 2.02886444e+12 1.15935111e+12 2.89837777e+11]


[None, None, None]

In [116]:
a2 = a2.reshape(m,nH,nW,nC)
print("a2{}: \n{}".format(a2.shape, a2[0,:,:,0]))

a2(1, 4, 4, 1): 
[[28. 38. 28. 14.]
 [46. 59. 40. 17.]
 [46. 56. 35. 12.]
 [30. 35. 20.  5.]]


In [117]:
caches3 = CacheForConv(caches2[1],caches2[0])
print("caches3[0]{}: \n{}".format(caches3[0].shape,caches3[0]))
#caches2[1][0] = [a.reshape(1,len(a),1,1) for a in caches2[1][0]]
#print("caches2[1][0][0]: \n",caches2[1][0])

caches3[0](1, 4, 4, 1): 
[[[[28.]
   [38.]
   [28.]
   [14.]]

  [[46.]
   [59.]
   [40.]
   [17.]]

  [[46.]
   [56.]
   [35.]
   [12.]]

  [[30.]
   [35.]
   [20.]
   [ 5.]]]]


In [118]:
delta = np.array([1,0,1,2,2,0,2,1,1,0,1,1,2,2,0,1]).reshape(4,4)
print("delta{}: \n{}".format(delta.shape,delta))

delta(4, 4): 
[[1 0 1 2]
 [2 0 2 1]
 [1 0 1 1]
 [2 2 0 1]]


In [119]:
nablaConvW = backPropagationConv(caches3, delta, Empty)
#nablaConvW = backPropagationConv((caches2[1][0][0],caches2[1][1],caches2[0][1],caches2[0][2],caches2[0][3]), delta, Empty)

a(1, 4, 4, 1): 
[[28. 38. 28. 14.]
 [46. 59. 40. 17.]
 [46. 56. 35. 12.]
 [30. 35. 20.  5.]]
w(3, 3, 1): 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [120]:
print("nablaConvW{}: \n{}".format(nablaConvW.shape,nablaConvW[...,0]))

nablaConvW(3, 3, 1): 
[[120. 108. 153.]
 [138. 115. 144.]
 [176. 105.  52.]]
