In [1]:
import numpy as np
import matplotlib.pyplot as plt
from Pad import PadZero
from FC import forwardPass, backPropagation
from Conv import feedForwardConv, Empty

In [2]:
def CacheForConv(cache1,cache2):
    cache = [cache1[0][0].copy(),cache2[1].copy(),cache2[2],cache2[3].copy()]
    shape = cache2[0].shape
    cache[0] = cache[0].reshape(shape)
    return cache

In [3]:
def backPropagationConv(cache, delta, activationFunctionPrime = Empty):
    (a,w,b,hyperparameters) = cache
    (m,nH,nW,nC) = a.shape
    (f,f,nC) = w.shape
    stride = hyperparameters["stride"]
    pad = hyperparameters["padding"]
    nablaW = np.zeros(w.shape)
    print("a{}: \n{}".format(a.shape,a[0,:,:,0]))
    print("w{}: \n{}".format(w.shape,w[...,0]))
    for m1 in range(m):
        for i,h1 in enumerate(range(0,nH-f+1,stride)):
            for j,w1 in enumerate(range(0,nW-f+1,stride)):
                for c1 in range(nC):
                    
                    '''print("\n\nm1: {}\ni:{} h1:{}\nj:{} w1:{}\nc1:{}".format(m1,i,h1,j,w1,c1))
                    print("W1: \n",nablaW[:,:,c1])
                    print("a: \n", a[m1,h1:h1+f,w1:w1+f,c1])
                    print("delta: \n",delta[h1:h1+f,w1:w1+f])'''
                    
                    newW = a[m1,h1:h1+f,w1:w1+f,c1] * delta[h1:h1+f,w1:w1+f]
                    nablaW[:,:,c1] += newW
                    
                    '''print("W2: \n",newW)
                    print("W: \n",nablaW[:,:,c1])'''
                    
    return nablaW

In [4]:
m = 1
nH = 4
nW = 4
nC = 1

sizeFilter = 3
stride = 1
pad = 1

x = np.random.randint(0,16,(m,nH,nW,nC))
#x = np.array([1,2,0,2,2,1,0,0,2,0,0,0,2,2,0,0]).reshape(m,nH,nW,nC)
print("x{}: \n{}".format(x.shape,x[0,:,:,0]))

wConv = np.random.randint(0,2,(sizeFilter,sizeFilter,nC))
#wConv = np.ones((sizeFilter,sizeFilter,nC), dtype = np.int32)
print("\nwConv{}: \n{}".format(wConv.shape, wConv[:,:,0]))

b = np.random.randint(0,2,(1,1,nC))
#b = 0

hyperparameters = {"stride": stride, "padding":pad}
caches2 = []

x(1, 4, 4, 1): 
[[13  0 12 10]
 [11  5 13  2]
 [ 1 11 10  1]
 [ 8  3 14 14]]

wConv(3, 3, 1): 
[[0 0 1]
 [0 0 0]
 [0 1 1]]


In [5]:
a1, cache = feedForwardConv(x,wConv,b,hyperparameters, Empty)

print("a1{}: \n{}".format(a1.shape, a1[0,:,:,0]))


a1(1, 4, 4, 1): 
[[25. 27. 24. 11.]
 [21. 42. 30. 10.]
 [25. 39. 39. 23.]
 [20. 19. 10.  9.]]


In [6]:
a2, cache = feedForwardConv(a1,wConv,b,hyperparameters, Empty)

print("a2{}: \n{}".format(a2.shape, a2[0,:,:,0]))

a2(1, 4, 4, 1): 
[[ 72.  81.  49.  19.]
 [100. 111.  82.  32.]
 [ 90.  68.  38.  18.]
 [ 48.  48.  32.   9.]]


In [7]:
caches2.append(cache)

In [8]:
a2 = a2.reshape(a1[0,0,:,0].shape[0] * a1[0,:,0,0].shape[0], 1)

In [9]:
print("a2{}: \n{}".format(a2.shape,a2))

a2(16, 1): 
[[ 72.]
 [ 81.]
 [ 49.]
 [ 19.]
 [100.]
 [111.]
 [ 82.]
 [ 32.]
 [ 90.]
 [ 68.]
 [ 38.]
 [ 18.]
 [ 48.]
 [ 48.]
 [ 32.]
 [  9.]]


In [10]:
#a = np.array([6,6,5,2,8,8,5,2,9,9,3,0,6,6,2,0], dtype = np.float).reshape(16,1)
#a = np.array([28,38,28,14,46,59,40,17,46,56,35,12,30,35,20,5], dtype = np.float).reshape(16,1)

size = [a2.shape[0],3,2]

m = 1

y = np.array([1,0]).reshape(size[-1],m)
#x = np.array([[1,2,3,1],[3,2,1,1]]).reshape(size[0],m)
x = a2
print("x{}: \n{}".format(x.shape,x))

#w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
w1 = np.array([[1,3,2,3,1,2,2,2,2,2,3,1,2,2,1,1],[1,1,2,1,1,3,1,3,3,1,3,3,2,3,1,1],[1,3,2,3,1,3,1,2,3,1,3,1,3,3,3,2]])
w2 = np.array([[1,2,1],[1,1,2]])
w = [w1,w2]
print("w: \n",w)

#b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
b1 = np.array([[1,3,3]]).reshape(3,1)
b2 = np.array([[1,2]]).reshape(2,1)
b = [b1,b2]
print("b: \n",b)

learningRate = 1

hyperparameters = {"learningRate":learningRate}


x(16, 1): 
[[ 72.]
 [ 81.]
 [ 49.]
 [ 19.]
 [100.]
 [111.]
 [ 82.]
 [ 32.]
 [ 90.]
 [ 68.]
 [ 38.]
 [ 18.]
 [ 48.]
 [ 48.]
 [ 32.]
 [  9.]]
w: 
 [array([[1, 3, 2, 3, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 1, 1],
       [1, 1, 2, 1, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 1],
       [1, 3, 2, 3, 1, 3, 1, 2, 3, 1, 3, 1, 3, 3, 3, 2]]), array([[1, 2, 1],
       [1, 1, 2]])]
b: 
 [array([[1],
       [3],
       [3]]), array([[1],
       [2]])]


In [11]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters,Empty)

print("yHat: \n",yHat)

yHat: 
 [[6969.]
 [7223.]]


In [12]:
caches2.append(cache)



In [13]:
nablaB, nablaW, delta = backPropagation(caches2[1], Empty)
print(nablaW.shape)
[print(newW) for newW in nablaW]

(3, 16)
[1.23440680e+13 1.38870765e+13 8.40082407e+12 3.25746239e+12
 1.71445389e+13 1.90304382e+13 1.40585219e+13 5.48625245e+12
 1.54300850e+13 1.16582865e+13 6.51492479e+12 3.08601700e+12
 8.22937868e+12 8.22937868e+12 5.48625245e+12 1.54300850e+12]
[1.79615846e+13 2.02067826e+13 1.22238562e+13 4.73986260e+12
 2.49466452e+13 2.76907762e+13 2.04562491e+13 7.98292648e+12
 2.24519807e+13 1.69637188e+13 9.47972519e+12 4.49039614e+12
 1.19743897e+13 1.19743897e+13 7.98292648e+12 2.24519807e+12]
[2.11814091e+13 2.38290853e+13 1.44151257e+13 5.58953852e+12
 2.94186238e+13 3.26546724e+13 2.41232715e+13 9.41395961e+12
 2.64767614e+13 2.00046642e+13 1.11790770e+13 5.29535228e+12
 1.41209394e+13 1.41209394e+13 9.41395961e+12 2.64767614e+12]


[None, None, None]

In [14]:
a2 = a2.reshape(m,nH,nW,nC)
print("a2{}: \n{}".format(a2.shape, a2[0,:,:,0]))

a2(1, 4, 4, 1): 
[[ 72.  81.  49.  19.]
 [100. 111.  82.  32.]
 [ 90.  68.  38.  18.]
 [ 48.  48.  32.   9.]]


In [15]:
caches3 = CacheForConv(caches2[1],caches2[0])
print("caches3[0]{}: \n{}".format(caches3[0].shape,caches3[0]))
#caches2[1][0] = [a.reshape(1,len(a),1,1) for a in caches2[1][0]]
#print("caches2[1][0][0]: \n",caches2[1][0])

caches3[0](1, 4, 4, 1): 
[[[[ 72.]
   [ 81.]
   [ 49.]
   [ 19.]]

  [[100.]
   [111.]
   [ 82.]
   [ 32.]]

  [[ 90.]
   [ 68.]
   [ 38.]
   [ 18.]]

  [[ 48.]
   [ 48.]
   [ 32.]
   [  9.]]]]


In [16]:
delta = np.array([1,0,1,2,2,0,2,1,1,0,1,1,2,2,0,1]).reshape(4,4)
print("delta{}: \n{}".format(delta.shape,delta))

delta(4, 4): 
[[1 0 1 2]
 [2 0 2 1]
 [1 0 1 1]
 [2 2 0 1]]


In [17]:
nablaConvW = backPropagationConv(caches3, delta, Empty)
#nablaConvW = backPropagationConv((caches2[1][0][0],caches2[1][1],caches2[0][1],caches2[0][2],caches2[0][3]), delta, Empty)

a(1, 4, 4, 1): 
[[ 72.  81.  49.  19.]
 [100. 111.  82.  32.]
 [ 90.  68.  38.  18.]
 [ 48.  48.  32.   9.]]
w(3, 3, 1): 
[[0 0 1]
 [0 0 0]
 [0 1 1]]


In [18]:
print("nablaConvW{}: \n{}".format(nablaConvW.shape,nablaConvW[...,0]))

nablaConvW(3, 3, 1): 
[[272. 213. 283.]
 [290. 202. 252.]
 [282. 134.  65.]]
