In [181]:
import numpy as np

In [182]:
def Sigmoid(x):
    return (np.exp(x))/((np.exp(x)) + 1)
def SigmoidPrime(x):
    return Sigmoid(x) * (1 - Sigmoid(x))

In [183]:
def Empty(x):
    return x

In [184]:
def forwardPass(x,y,w,b,hyperparameters, activationFunction = Sigmoid):
    learningRate = hyperparameters["learningRate"]
    aS = []
    aS.append(x)
    zS = []
    zS.append(x)
    
    for i in range(len(w)):
        z = w[i].dot(aS[i]) + b[i]
        zS.append(z)
        #print("{})z: {}".format(i,zS[-1]))
        a = activationFunction(z)
        aS.append(a)
        #print("{})a: {}".format(i,aS[-1]))
    
    yHat = aS[-1]
    cache = [aS,y,w,b,hyperparameters]
    
    return yHat, cache

In [185]:
def backPropagation(caches2, primeActivationFunction = SigmoidPrime):
    (aS,y,w,b,hyperparameters) = caches2
    #aS = [a.reshape(len(a[0]),1) for a in aS]
    delta = (aS[-1] - y) * primeActivationFunction(aS[-1])
    nablaB = delta
    nablaW = delta.dot(aS[-2].T)
    
    for l in range(2,len(aS)):
        '''
        print("w[{}]{}: \n{}".format(-l+1,w[-l+1].shape, w[-l+1]))
        print("delta1{}: \n{}".format(delta.shape, delta))
        print("aS[{}]{}: \n{}".format(-l, aS[-l].shape, aS[-l]))
        '''
        delta = w[-l+1].T.dot(delta) * primeActivationFunction(aS[-l])
        nablaB = delta
        nablaW = delta.dot(aS[-l-1].T)
        #print("delta2{}: \n{}".format(delta.shape, delta))
    
    return nablaB, nablaW, delta

In [186]:
#a = np.array([6,6,5,2,8,8,5,2,9,9,3,0,6,6,2,0], dtype = np.float).reshape(16,1)
a = np.array([28,38,28,14,46,59,40,17,46,56,35,12,30,35,20,5], dtype = np.float).reshape(16,1)
print("a{}: \n{}".format(a.shape,a))

size = [a.shape[0],3,2]
m = 1

y = np.array([1,0]).reshape(size[-1],m)
#x = np.array([[1,2,3,1],[3,2,1,1]]).reshape(size[0],m)
x = a

#w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
w1 = np.array([[1,3,2,3,1,2,2,2,2,2,3,1,2,2,1,1],[1,1,2,1,1,3,1,3,3,1,3,3,2,3,1,1],[1,3,2,3,1,3,1,2,3,1,3,1,3,3,3,2]])
w2 = np.array([[1,2,1],[1,1,2]])
w = [w1,w2]
print("w: \n",w)

#b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
b1 = np.array([[1,3,3]]).reshape(3,1)
b2 = np.array([[1,2]]).reshape(2,1)
b = [b1,b2]
print("b: \n",b)

learningRate = 1
caches2 = []
hyperparameters = {"learningRate":learningRate}


a(16, 1): 
[[28.]
 [38.]
 [28.]
 [14.]
 [46.]
 [59.]
 [40.]
 [17.]
 [46.]
 [56.]
 [35.]
 [12.]
 [30.]
 [35.]
 [20.]
 [ 5.]]
w: 
 [array([[1, 3, 2, 3, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 1, 1],
       [1, 1, 2, 1, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 1],
       [1, 3, 2, 3, 1, 3, 1, 2, 3, 1, 3, 1, 3, 3, 3, 2]]), array([[1, 2, 1],
       [1, 1, 2]])]
b: 
 [array([[1],
       [3],
       [3]]), array([[1],
       [2]])]


In [187]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters,Empty)

print("yHat{}: \n{}".format(yHat.shape,yHat))

yHat(2, 1): 
[[4068.]
 [4207.]]


In [188]:
caches2.append(cache)


In [189]:
nablaB,nablaW, delta = backPropagation(caches2[0],Empty)
print("nablaW{}: \n{}".format(nablaW.shape, nablaW))

nablaW(3, 16): 
[[9.54021263e+11 1.29474314e+12 9.54021263e+11 4.77010632e+11
  1.56732065e+12 2.01025909e+12 1.36288752e+12 5.79227196e+11
  1.56732065e+12 1.90804253e+12 1.19252658e+12 4.08866256e+11
  1.02216564e+12 1.19252658e+12 6.81443760e+11 1.70360940e+11]
 [1.39077752e+12 1.88748378e+12 1.39077752e+12 6.95388762e+11
  2.28484879e+12 2.93056693e+12 1.98682503e+12 8.44400640e+11
  2.28484879e+12 2.78155505e+12 1.73847191e+12 5.96047510e+11
  1.49011878e+12 1.73847191e+12 9.93412517e+11 2.48353129e+11]
 [1.62309155e+12 2.20276711e+12 1.62309155e+12 8.11545776e+11
  2.66650755e+12 3.42008577e+12 2.31870222e+12 9.85448443e+11
  2.66650755e+12 3.24618311e+12 2.02886444e+12 6.95610666e+11
  1.73902666e+12 2.02886444e+12 1.15935111e+12 2.89837777e+11]]


In [190]:
(a2,y2,w2,b2,hyp2) = caches2[0]

In [191]:
g = [print("{})a: \n{}".format(i,a)) for i,a in enumerate(a2)]

0)a: 
[[28.]
 [38.]
 [28.]
 [14.]
 [46.]
 [59.]
 [40.]
 [17.]
 [46.]
 [56.]
 [35.]
 [12.]
 [30.]
 [35.]
 [20.]
 [ 5.]]
1)a: 
[[ 995.]
 [ 978.]
 [1116.]]
2)a: 
[[4068.]
 [4207.]]
