In [74]:
import numpy as np

In [75]:
def Sigmoid(x):
    return (np.exp(x))/((np.exp(x)) + 1)
def SigmoidPrime(x):
    return Sigmoid(x) * (1 - Sigmoid(x))

In [76]:
def Empty(x):
    return x

In [77]:
def forwardPass(x,y,w,b,hyperparameters, activationFunction = Sigmoid):
    learningRate = hyperparameters["learningRate"]
    aS = []
    aS.append(x)
    zS = []
    zS.append(x)
    
    for i in range(len(w)):
        z = w[i].dot(aS[i]) + b[i]
        zS.append(z)
        #print("{})z: {}".format(i,zS[-1]))
        a = activationFunction(z)
        aS.append(a)
        #print("{})a: {}".format(i,aS[-1]))
    
    yHat = aS[-1]
    cache = [aS,y,w,b,hyperparameters]
    
    return yHat, cache

In [78]:
def backPropagation(caches2, primeActivationFunction = SigmoidPrime):
    (aS,y,w,b,hyperparameters) = caches2
    #aS = [a.reshape(len(a[0]),1) for a in aS]
    delta = (aS[-1] - y) * primeActivationFunction(aS[-1])
    nablaB = delta
    nablaW = delta.dot(aS[-2].T)
    
    for l in range(2,len(aS)):
        
        print("w[{}]{}: \n{}".format(-l+1,w[-l+1].shape, w[-l+1]))
        print("delta1{}: \n{}".format(delta.shape, delta))
        print("aS[{}]{}: \n{}".format(-l, aS[-l].shape, aS[-l]))
        
        delta = w[-l+1].T.dot(delta) * primeActivationFunction(aS[-l])
        nablaB = delta
        nablaW = delta.dot(aS[-l-1].T)
        print("delta2{}: \n{}".format(delta.shape, delta))
    
    return nablaB, nablaW, delta

In [79]:
#a = np.array([6,6,5,2,8,8,5,2,9,9,3,0,6,6,2,0], dtype = np.float).reshape(16,1)
a = np.array([28,38,28,14,46,59,40,17,46,56,35,12,30,35,20,5], dtype = np.float).reshape(16,1)
print("a{}: \n{}".format(a.shape,a))

#size = [a.shape[0],3,2]
size = [3,3,2]
m = 3

#y = np.array([1,0]).reshape(size[-1],m)
y = np.random.randint(0,2,(size[-1],m)).reshape(size[-1],m)
x = np.random.randint(0,16,(size[0],m))
#x = np.array([[1,2,3,1],[3,2,1,1]]).reshape(size[0],m)
#x = a

w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
#w1 = np.array([[1,3,2,3,1,2,2,2,2,2,3,1,2,2,1,1],[1,1,2,1,1,3,1,3,3,1,3,3,2,3,1,1],[1,3,2,3,1,3,1,2,3,1,3,1,3,3,3,2]])
#w2 = np.array([[1,2,1],[1,1,2]])
#w = [w1,w2]
print("w: \n",w)

b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
#b1 = np.array([[1,3,3]]).reshape(3,1)
#b2 = np.array([[1,2]]).reshape(2,1)
#b = [b1,b2]
print("b: \n",b)

learningRate = 1
caches2 = []
hyperparameters = {"learningRate":learningRate}


a(16, 1): 
[[28.]
 [38.]
 [28.]
 [14.]
 [46.]
 [59.]
 [40.]
 [17.]
 [46.]
 [56.]
 [35.]
 [12.]
 [30.]
 [35.]
 [20.]
 [ 5.]]
w: 
 [array([[2, 1, 1],
       [1, 3, 3],
       [2, 2, 3]]), array([[3, 1, 1],
       [2, 2, 2]])]
b: 
 [array([[3],
       [1],
       [3]]), array([[1],
       [1]])]


In [80]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters,Empty)

print("yHat{}: \n{}".format(yHat.shape,yHat))

yHat(2, 3): 
[[318 334 305]
 [435 467 441]]


In [81]:
caches2.append(cache)


In [82]:
nablaB,nablaW, delta = backPropagation(caches2[0],Empty)
print("nablaW{}: \n{}".format(nablaW.shape, nablaW))

w[-1](2, 3): 
[[3 1 1]
 [2 2 2]]
delta1(2, 3): 
[[101124 111222  92720]
 [188790 218089 194481]]
aS[-2](3, 3): 
[[50 50 42]
 [82 92 93]
 [85 91 85]]
delta2(3, 3): 
[[34047600 38492200 28019124]
 [39253728 50360800 44796426]
 [40689840 49813400 40942970]]
nablaW(3, 3): 
[[ 933588820 1295209060 1339729736]
 [1198634866 1758427798 1803245900]
 [1191126930 1709306990 1758867260]]


In [83]:
(a2,y2,w2,b2,hyp2) = caches2[0]

In [84]:
g = [print("{})a: \n{}".format(i,a)) for i,a in enumerate(a2)]

0)a: 
[[12 10  5]
 [11 13 15]
 [12 14 14]]
1)a: 
[[50 50 42]
 [82 92 93]
 [85 91 85]]
2)a: 
[[318 334 305]
 [435 467 441]]
