In [211]:
import numpy as np
import matplotlib.pyplot as plt
from Pad import PadZero

In [212]:
def Sigmoid(x):
    return (np.exp(x))/((np.exp(x)) + 1)
def SigmoidPrime(x):
    return Sigmoid(x) * (1 - Sigmoid(x))

In [213]:
def Empty(x):
    return x

In [214]:
def feedForwardConv(prevA,w,b,hyperparameters, activationFunction = Sigmoid):
    (m, oldNH, oldNW, nC) = prevA.shape
    (f,f,nC) = w.shape
    stride = hyperparameters["stride"]
    pad = hyperparameters["padding"]
    
    newNH = int((oldNH - f + 2*pad)/stride) + 1
    newNW = int((oldNH - f + 2*pad)/stride) + 1
    
    z = np.zeros((m,newNH, newNW, nC))
    a = np.zeros((m,newNH, newNW, nC))
    
    if (pad != 0):
        prevA = PadZero(prevA, pad)
    
    for m1 in range(m):
        for i,h1 in enumerate(range(0,newNH,stride)):
            for j,w1 in enumerate(range(0,newNW, stride)):
                for c in range(nC):
                    z[m1,i,j,c] = np.sum((prevA[m1,h1:h1+f,w1:w1+f,c] * w[...,c]) + b)#[...,с] нужно, чтобы размерности совпали
                    a[m1,i,j,c] = activationFunction(z[m1,i,j,c])

    assert (m,newNH,newNW,nC) == a.shape
    
    cache = (a, w, b, hyperparameters)
    
    return a, cache

In [225]:
def backPropagationConv(cache, delta, activationFunctionPrime = SigmoidPrime):
    (a,w,b,hyperparameters) = cache[0]
    (m,nH,nW,nC) = a.shape
    stride = hyperparameters["stride"]
    pad = hyperparameters["padding"]
    for m1 in range(m):
        for i,h1 in enumerate(range(0,nH,stride)):
            for j,w1 in enumerate(range(0,nW,stride)):
                for c1 in range(c):
                    
    return a

In [220]:
m = 1
nH = 4
nW = 4
nC = 1
sizeFilter = 3
stride = 1
pad = 1
#x = np.random.randint(0,16,(m,nH,nW,nC))
x = np.array([1,2,0,2,2,1,0,0,2,0,0,0,2,2,0,0]).reshape(m,nH,nW,nC)
print(x[0,:,:,0])
print("shape: ", x.shape)
w = np.ones((sizeFilter,sizeFilter,nC), dtype = np.int32)
b = 0
hyperparameters = {"stride": stride, "padding":pad}
caches2 = []
print("filter: \n", w[:,:,0])


[[1 2 0 2]
 [2 1 0 0]
 [2 0 0 0]
 [2 2 0 0]]
shape:  (1, 4, 4, 1)
filter: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [219]:
a, cache = feedForwardConv(x,w,b,hyperparameters, Empty)

print("a: \n",a[0,:,:,0])


a: 
 [[6. 6. 5. 2.]
 [8. 8. 5. 2.]
 [9. 9. 3. 0.]
 [6. 6. 2. 0.]]


In [222]:
caches2.append(cache)

In [226]:
activations = backPropagationConv(caches2)

In [228]:
print(activations[0,:,:,0])

[[6. 6. 5. 2.]
 [8. 8. 5. 2.]
 [9. 9. 3. 0.]
 [6. 6. 2. 0.]]
