In [1]:
import numpy as np

In [45]:
y = np.array([[1,0]]).reshape(2,1)
print(y.shape)

(2, 1)


In [21]:
w1 = np.array([[5,6,3,2,1,7],[7,3,9,8,3,2],[5,3,3,4,1,8],[1,1,4,5,7,6],[2,4,3,6,8,9],[1,2,4,3,5,7]])
b1 = 0

In [22]:
print("w1: \n",w1)
print("shape: ",w1.shape)

w1: 
 [[5 6 3 2 1 7]
 [7 3 9 8 3 2]
 [5 3 3 4 1 8]
 [1 1 4 5 7 6]
 [2 4 3 6 8 9]
 [1 2 4 3 5 7]]
shape:  (6, 6)


In [23]:
x = np.array([2,5,3,1,4,2]).reshape(6,1)

In [24]:
print("x: \n",x)
print("shape: ",x.shape)

x: 
 [[2]
 [5]
 [3]
 [1]
 [4]
 [2]]
shape:  (6, 1)


In [30]:
z1 = w1.dot(x) + b1
a1 = z1
print("a1: \n",a1)
print("a1.shape: ", a1.shape)

a1: 
 [[69]
 [80]
 [58]
 [64]
 [89]
 [61]]
a1.shape:  (6, 1)


In [31]:
w2 = np.array([[5,3,1,2,8,9],[4,5,8,7,6,7],[3,4,6,5,9,1],[2,3,2,1,1,3]])
b2 = 0

In [32]:
print("w2: \n",w2)
print("shape: ",w2.shape)

w2: 
 [[5 3 1 2 8 9]
 [4 5 8 7 6 7]
 [3 4 6 5 9 1]
 [2 3 2 1 1 3]]
shape:  (4, 6)


In [33]:
z2 = w2.dot(a1) + b2
a2 = z2
print("a2: \n",a2)
print("a2.shape: ", a2.shape)

a2: 
 [[2032]
 [2549]
 [2057]
 [ 830]]
a2.shape:  (4, 1)


In [36]:
w3 = np.array([[3,2,5,9],[2,3,5,7],[8,1,4,6],[9,8,2,7],[2,3,4,3],[1,1,7,9]])
b3 = 0

In [37]:
print("w3: \n",w3)
print("shape: ",w3.shape)

w3: 
 [[3 2 5 9]
 [2 3 5 7]
 [8 1 4 6]
 [9 8 2 7]
 [2 3 4 3]
 [1 1 7 9]]
shape:  (6, 4)


In [38]:
z3 = w3.dot(a2) + b3
a3 = z3
print("a3: \n",a3)
print("a3.shape: ", a3.shape)

a3: 
 [[28949]
 [27806]
 [32013]
 [48604]
 [22429]
 [26450]]
a3.shape:  (6, 1)


In [42]:
w4 = np.array([[2,3,1,9,8,5],[5,4,8,7,1,3]])
b4 = 0

In [43]:
print("w4: \n",w4)
print("shape: ",w4.shape)

w3: 
 [[3 2 5 9]
 [2 3 5 7]
 [8 1 4 6]
 [9 8 2 7]
 [2 3 4 3]
 [1 1 7 9]]
shape:  (6, 4)


In [44]:
z4 = w4.dot(a3) + b4
a4 = z4
print("a4: \n",a4)
print("a4.shape: ", a4.shape)

a4: 
 [[922447]
 [954080]]
a4.shape:  (2, 1)


In [62]:
d4 = (a4-y) * a4 *(1-a4)
print("d4: \n",d4)
print("shape: ", d4.shape)

d4: 
 [[-1718652284]
 [  115983360]]
shape:  (2, 1)


In [63]:
d3 = w4.T.dot(d4) * a3 * (1 - a3)
print("d3: \n", d3)
print("shape: ", d3.shape)

d3: 
 [[  403351264]
 [ -314062792]
 [ 1624335248]
 [  942946992]
 [-1189016960]
 [-1051833320]]
shape:  (6, 1)


In [64]:
d2 = w3.T.dot(d3) * a2 * (1 - a2)
print("d2: \n", d2)
print("shape: ", d2.shape)

d2: 
 [[ 1514846848]
 [-1840927808]
 [ -377282048]
 [ 1103922272]]
shape:  (4, 1)


In [65]:
d1 = w2.T.dot(d2) * a1 * (1 - a1)
print("d1: \n", d1)
print("shape: ", d1.shape)

d1: 
 [[-1929395456]
 [-1191088640]
 [  906634112]
 [ -520394752]
 [ -844121344]
 [-1386575488]]
shape:  (6, 1)


In [71]:
dw1 = d1.dot(x.T)
print("dw1: \n",dw1)
print("shape: ", dw1.shape)

dw1: 
 [[  436176384 -1057042688 -1493219072 -1929395456   872352768   436176384]
 [ 1912790016 -1660475904   721701376 -1191088640  -469387264  1912790016]
 [ 1813268224   238203264 -1575064960   906634112  -668430848  1813268224]
 [-1040789504  1692993536 -1561184256  -520394752 -2081579008 -1040789504]
 [-1688242688    74360576  1762603264  -844121344   918481920 -1688242688]
 [ 1521816320  1657057152   135240832 -1386575488 -1251334656  1521816320]]
shape:  (6, 6)


In [72]:
dw2 = d2.dot(a1.T)
print("dw2: \n",dw2)
print("shape: ", dw2.shape)

dw2: 
 [[ 1445217408   928663552  1961771264 -1834049536  1677383296 -2083622784]
 [ 1825000128 -1245336576   600369536 -1855262720  -633817664  -627446592]
 [ -262657536  -117792768  -407522304  1623752704   781636096 -1539368448]
 [-1138774560 -1880531456  -397017664  1931548672  -535165600 -1380218144]]
shape:  (4, 6)


In [73]:
dw3 = d3.dot(a2.T)
print("dw3: \n",dw3)
print("shape: ", dw3.shape)

dw3: 
 [[ -728985088  1645188192   764861920  -225899968]
 [ 1774533760 -1682139752 -1782068744  1320887696]
 [ 2114340608    82073808  -226951152  -421475104]
 [  512873728 -1609803152 -1683255248   961955488]
 [ 1984124928  1442679936 -1971495296   958401280]
 [ 1568407168 -1063539976  1042377944 -1143294512]]
shape:  (6, 4)


In [74]:
dw4 = d4.dot(a3.T)
print("dw4: \n",dw4)
print("shape: ", dw4.shape)

dw4: 
 [[ -363812652  1255693688  -684505932  -556671632  -320596236  -419050936]
 [-1062136832  -487131136  2123559936 -2036830208 -1359399936  1153222656]]
shape:  (2, 6)
