In [108]:
import numpy as np

In [109]:
def Sigmoid(x):
    return (np.exp(x))/((np.exp(x)) + 1)
def SigmoidPrime(x):
    return Sigmoid(x) * (1 - Sigmoid(x))

In [110]:
def Empty(x):
    return x

In [111]:
def forwardPass(x,y,w,b,hyperparameters, activationFunction = Sigmoid):
    learningRate = hyperparameters["learningRate"]
    aS = []
    aS.append(x)
    zS = []
    zS.append(x)
    
    for i in range(len(w)):
        z = w[i].dot(aS[i]) + b[i]
        zS.append(z)
        a = activationFunction(z)
        aS.append(a)
    
    cache = (aS,y,w,b,hyperparameters)
    yHat = aS[-1]
    return yHat, cache

In [112]:
def backPropagation(caches2, primeActivationFunction = SigmoidPrime):
    aS = caches2[0][0]
    y = caches2[0][1]
    w = caches2[0][2]
    b = caches2[0][3]
    delta = (aS[-1] - y) * primeActivationFunction(aS[-1])
    nablaB = delta
    nablaW = delta.dot(aS[-2].T)
    
    for l in range(2,len(aS)):
        
        print("w[{}]{}: \n{}".format(-l+1,w[-l+1].shape, w[-l+1]))
        print("delta1{}: \n{}".format(delta.shape, delta))
        print("aS[{}]{}: \n{}".format(-l, aS[-l].shape, aS[-l]))
        
        delta = w[-l+1].T.dot(delta) * primeActivationFunction(aS[-l])
        nablaB = delta
        nablaW = delta.dot(aS[-l-1].T)
        print("delta2{}: \n{}".format(delta.shape, delta))
    
    return nablaB, nablaW

In [113]:
a = np.array([6,6,5,2,8,8,5,2,9,9,3,0,6,6,2,0], dtype = np.float).reshape(16,1)
print("a{}: \n{}".format(a.shape,a))
size = [a.shape[0],3,2]
m = 1
y = np.array([1,0]).reshape(size[-1],m)
#x = np.array([[1,2,3,1],[3,2,1,1]]).reshape(size[0],m)
x = a
w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
print(w[1].shape)
learningRate = 1
caches2 = []
hyperparameters = {"learningRate":learningRate}


a(16, 1): 
[[6.]
 [6.]
 [5.]
 [2.]
 [8.]
 [8.]
 [5.]
 [2.]
 [9.]
 [9.]
 [3.]
 [0.]
 [6.]
 [6.]
 [2.]
 [0.]]
(2, 3)


In [114]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters)

print("yHat: \n",yHat)

yHat: 
 [[0.99752738]
 [0.99908895]]


In [115]:
caches2.append(cache)


In [116]:
[print("{}: \n{}".format(i,ca[:][0])) for i,ca in enumerate(caches2)]
#[print("{}.{}: \n{}".format(j,i, caches[j])) for i in range(len(caches[0])) for j in range(len(caches2))]

0: 
[array([[6.],
       [6.],
       [5.],
       [2.],
       [8.],
       [8.],
       [5.],
       [2.],
       [9.],
       [9.],
       [3.],
       [0.],
       [6.],
       [6.],
       [2.],
       [0.]]), array([[1.],
       [1.],
       [1.]]), array([[0.99752738],
       [0.99908895]])]


[None]

In [117]:
bias,activations = backPropagation(caches2)
print(activations.shape)
[print(activ) for activ in activations]

w[-1](2, 3): 
[[1 1 1]
 [1 3 1]]
delta1(2, 1): 
[[-0.0004867]
 [ 0.1965155]]
aS[-2](3, 1): 
[[1.]
 [1.]
 [1.]]
delta2(3, 1): 
[[0.0385416 ]
 [0.11581618]
 [0.0385416 ]]
(3, 16)
[0.2312496 0.2312496 0.192708  0.0770832 0.3083328 0.3083328 0.192708
 0.0770832 0.3468744 0.3468744 0.1156248 0.        0.2312496 0.2312496
 0.0770832 0.       ]
[0.6948971  0.6948971  0.57908092 0.23163237 0.92652946 0.92652946
 0.57908092 0.23163237 1.04234565 1.04234565 0.34744855 0.
 0.6948971  0.6948971  0.23163237 0.        ]
[0.2312496 0.2312496 0.192708  0.0770832 0.3083328 0.3083328 0.192708
 0.0770832 0.3468744 0.3468744 0.1156248 0.        0.2312496 0.2312496
 0.0770832 0.       ]


[None, None, None]

In [118]:
(a2,y2,w2,b2,hyp2) = caches2[0]

In [119]:
[print(a) for a in a2]

[[6.]
 [6.]
 [5.]
 [2.]
 [8.]
 [8.]
 [5.]
 [2.]
 [9.]
 [9.]
 [3.]
 [0.]
 [6.]
 [6.]
 [2.]
 [0.]]
[[1.]
 [1.]
 [1.]]
[[0.99752738]
 [0.99908895]]


[None, None, None]