In [1]:
import numpy as np

In [161]:
def Sigmoid(x):
    return (np.exp(x))/((np.exp(x)) + 1)
def SigmoidPrime(x):
    return Sigmoid(x) * (1 - Sigmoid(x))

In [181]:
def forwardPass(x,y,w,b,hyperparameters, activationFunction = Sigmoid):
    learningRate = hyperparameters["learningRate"]
    aS = []
    aS.append(x)
    zS = []
    zS.append(x)
    
    for i in range(len(w)):
        z = w[i].dot(aS[i]) + b[i]
        zS.append(z)
        a = activationFunction(z)
        aS.append(a)
    
    cache = (aS,y,w,b,hyperparameters)
    yHat = aS[-1]
    return yHat, cache

In [284]:
def backPropagation(caches2, primeActivationFunction = SigmoidPrime):
    aS = caches2[0][0]
    y = caches2[0][1]
    w = caches2[0][2]
    b = caches2[0][3]
    delta = (aS[-1] - y) * SigmoidPrime(aS[-1])
    nablaB = delta
    nablaW = delta.dot(aS[-2].T)
    
    for l in range(2,len(aS)):
        '''
        print("w[{}]{}: \n{}".format(-l+1,w[-l+1].shape, w[-l+1]))
        print("delta1{}: \n{}".format(delta.shape, delta))
        print("aS[{}]{}: \n{}".format(-l, aS[-l].shape, aS[-l]))
        '''
        delta = w[-l+1].T.dot(delta) * SigmoidPrime(aS[-l])
        nablaB = delta
        nablaW = delta.dot(aS[-l].T)
        #print("delta2{}: \n{}".format(delta.shape, delta))
    return nablaW

In [285]:
size = [4,3,2]
m = 1
y = np.array([1,0]).reshape(size[-1],m)
x = np.array([1,2,3,1]).reshape(size[0],m)
w = [np.random.randint(1,4,(y,x)) for x,y in zip(size[:-1],size[1:])]
b = [np.random.randint(1,4,(y,1)) for y in size[1:]]
print(w[1].shape)
learningRate = 1
caches2 = []
hyperparameters = {"learningRate":learningRate}


(2, 3)


In [286]:
yHat, cache = forwardPass(x,y,w,b,hyperparameters)

print("yHat: \n",yHat)

yHat: 
 [[0.99752738]
 [0.9999546 ]]


In [287]:
caches2.append(cache)



In [288]:
[print("{}: \n{}".format(i,ca[:][0])) for i,ca in enumerate(caches2)]
#[print("{}.{}: \n{}".format(j,i, caches[j])) for i in range(len(caches[0])) for j in range(len(caches2))]

0: 
[array([[1],
       [2],
       [3],
       [1]]), array([[0.99999989],
       [0.99999969],
       [1.        ]]), array([[0.99752738],
       [0.9999546 ]])]


[None]

In [289]:
actiovations = backPropagation(caches2)
print(actiovations)

[[0.11587023 0.1158702  0.11587024]
 [0.07711924 0.07711922 0.07711924]
 [0.11577453 0.11577451 0.11577454]]
