In [1]:
import numpy as np

In [6]:
a = np.array([28,32,28,14,46,59,40,17,46,56,35,12,30,35,20,5], dtype = np.float).reshape(4,4)
d2 = np.array([[1,3,2,4],[4,2,2,1],[1,3,1,1],[1,1,4,2]])
w2 = np.ones((3,3))

In [3]:
print(a)

[[28. 32. 28. 14.]
 [46. 59. 40. 17.]
 [46. 56. 35. 12.]
 [30. 35. 20.  5.]]


In [4]:
print(d2)

[[1 3 2 4]
 [4 2 2 1]
 [1 3 1 1]
 [1 1 4 2]]


In [15]:
a1 = np.array([6,6,5,2,8,8,5,2,9,9,3,0,6,6,2,0], dtype = np.float).reshape(4,4)

d1 = np.zeros((4,4))
f = len(w2)
for h1 in range(len(a1)-f+1):
    for w1 in range(len(a1[0])-f+1):
        print("h1: ",h1)
        print("w1: ",w1)
        d1[h1:h1+f,w1:w1+f] = w2.T.dot(d2[h1:h1+f,w1:w1+f]) * a1[h1:h1+f,w1:w1+f] * (1 - a[h1:h1+f,w1:w1+f])

h1:  0
w1:  0
h1:  0
w1:  1
h1:  1
w1:  0
h1:  1
w1:  1


In [16]:
print(a1)

[[6. 6. 5. 2.]
 [8. 8. 5. 2.]
 [9. 9. 3. 0.]
 [6. 6. 2. 0.]]


In [17]:
print(d1)

[[ -972. -1488.  -675.  -156.]
 [-2160. -2784. -1365.  -128.]
 [-2430. -2970.  -714.    -0.]
 [-1044. -1224.  -266.    -0.]]
